var SPRITE_SHEET_MAP =
[
 [
  [
   [{x:0, y:0, img:"tile/road-ud.png"}], 
   [{x:1, y:0, img:"tile/road-lr.png"}], 
   [{x:2, y:0, img:"tile/road-ul.png"}], 
   [{x:3, y:0, img:"tile/road-ur.png"}], 
   [{x:4, y:0, img:"tile/road-ld.png"}], 
   [{x:5, y:0, img:"tile/road-rd.png"}], 
   [{x:6, y:0, img:"tile/road-t-crossing-u.png"}], 
   [{x:7, y:0, img:"tile/road-t-crossing-d.png"}], 
   [{x:8, y:0, img:"tile/road-t-crossing-l.png"}], 
   [{x:9, y:0, img:"tile/road-t-crossing-r.png"}], 
   [{x:10, y:0, img:"tile/road-x-crossing.png"}]], 
  [
   [{x:11, y:0, img:"tile/plains.png"}]], 
  [
   [{x:0, y:1, img:"tile/forest.png"}]], 
  [
   [{x:1, y:1, img:"tile/mountains.png"}]], 
  [
   [{x:2, y:1, img:"tile/water.png"}], 
   [{x:3, y:1, img:"tile/water-edge-t.png"}], 
   [{x:4, y:1, img:"tile/water-edge-b.png"}], 
   [{x:5, y:1, img:"tile/water-edge-l.png"}], 
   [{x:6, y:1, img:"tile/water-edge-r.png"}], 
   [{x:7, y:1, img:"tile/water-edge-tl.png"}], 
   [{x:8, y:1, img:"tile/water-edge-tr.png"}], 
   [{x:9, y:1, img:"tile/water-edge-bl.png"}], 
   [{x:10, y:1, img:"tile/water-edge-br.png"}], 
   [{x:11, y:1, img:"tile/water-corner-tl.png"}], 
   [{x:0, y:2, img:"tile/water-corner-tr.png"}], 
   [{x:1, y:2, img:"tile/water-corner-bl.png"}], 
   [{x:2, y:2, img:"tile/water-corner-br.png"}], 
   [{x:3, y:2, img:"tile/water-corner-tl-br.png"}], 
   [{x:4, y:2, img:"tile/water-corner-tr-bl.png"}], 
   [{x:5, y:2, img:"tile/water-corner-tl-tr.png"}], 
   [{x:6, y:2, img:"tile/water-corner-tl-bl.png"}], 
   [{x:7, y:2, img:"tile/water-corner-tr-br.png"}], 
   [{x:8, y:2, img:"tile/water-corner-bl-br.png"}], 
   [{x:9, y:2, img:"tile/water-river-ud.png"}], 
   [{x:10, y:2, img:"tile/water-river-lr.png"}], 
   [{x:11, y:2, img:"tile/water-river-ul.png"}], 
   [{x:0, y:3, img:"tile/water-river-ur.png"}], 
   [{x:1, y:3, img:"tile/water-river-ld.png"}], 
   [{x:2, y:3, img:"tile/water-river-rd.png"}], 
   [{x:3, y:3, img:"tile/water-corner-tl-tr-bl.png"}], 
   [{x:4, y:3, img:"tile/water-corner-tl-bl-br.png"}], 
   [{x:5, y:3, img:"tile/water-corner-tr-bl-br.png"}], 
   [{x:6, y:3, img:"tile/water-corner-tl-tr-br.png"}], 
   [{x:7, y:3, img:"tile/water-corner-tl-tr-bl-br.png"}], 
   [{x:8, y:3, img:"tile/water-river-u.png"}], 
   [{x:9, y:3, img:"tile/water-river-l.png"}], 
   [{x:10, y:3, img:"tile/water-river-r.png"}], 
   [{x:11, y:3, img:"tile/water-river-d.png"}]], 
  [
   [{x:0, y:4, img:"tile/city.png"}, {x:1, y:4, img:"tile/city_1.png"}, {x:2, y:4, img:"tile/city_2.png"}, {x:3, y:4, img:"tile/city_3.png"}, {x:4, y:4, img:"tile/city_4.png"}]], 
  [
   [{x:5, y:4, img:"tile/base.png"}, {x:6, y:4, img:"tile/base_1.png"}, {x:7, y:4, img:"tile/base_2.png"}, {x:8, y:4, img:"tile/base_3.png"}, {x:9, y:4, img:"tile/base_4.png"}]], 
  [
   [{x:10, y:4, img:"tile/fort.png"}, {x:11, y:4, img:"tile/fort_1.png"}, {x:0, y:5, img:"tile/fort_2.png"}, {x:1, y:5, img:"tile/fort_3.png"}, {x:2, y:5, img:"tile/fort_4.png"}]], 
  [
   [{x:3, y:5, img:"tile/airport.png"}, {x:4, y:5, img:"tile/airport_1.png"}, {x:5, y:5, img:"tile/airport_2.png"}, {x:6, y:5, img:"tile/airport_3.png"}, {x:7, y:5, img:"tile/airport_4.png"}]], 
  [
   [{x:8, y:5, img:"tile/port.png"}, {x:9, y:5, img:"tile/port_1.png"}, {x:10, y:5, img:"tile/port_2.png"}, {x:11, y:5, img:"tile/port_3.png"}, {x:0, y:6, img:"tile/port_4.png"}]], 
  [
   [{x:1, y:6, img:"tile/beach-u.png"}], 
   [{x:2, y:6, img:"tile/beach-d.png"}], 
   [{x:3, y:6, img:"tile/beach-l.png"}], 
   [{x:4, y:6, img:"tile/beach-r.png"}]]], 
 [
  [null, {x:5, y:6, img:"unit/infantry_1.png"}, {x:6, y:6, img:"unit/infantry_2.png"}, {x:7, y:6, img:"unit/infantry_3.png"}, {x:8, y:6, img:"unit/infantry_4.png"}], 
  [null, {x:9, y:6, img:"unit/at-infantry_1.png"}, {x:10, y:6, img:"unit/at-infantry_2.png"}, {x:11, y:6, img:"unit/at-infantry_3.png"}, {x:0, y:7, img:"unit/at-infantry_4.png"}], 
  [null, {x:1, y:7, img:"unit/scout_1.png"}, {x:2, y:7, img:"unit/scout_2.png"}, {x:3, y:7, img:"unit/scout_3.png"}, {x:4, y:7, img:"unit/scout_4.png"}], 
  [null, {x:5, y:7, img:"unit/light_tank_1.png"}, {x:6, y:7, img:"unit/light_tank_2.png"}, {x:7, y:7, img:"unit/light_tank_3.png"}, {x:8, y:7, img:"unit/light_tank_4.png"}], 
  [null, {x:9, y:7, img:"unit/medium_tank_1.png"}, {x:10, y:7, img:"unit/medium_tank_2.png"}, {x:11, y:7, img:"unit/medium_tank_3.png"}, {x:0, y:8, img:"unit/medium_tank_4.png"}], 
  [null, {x:1, y:8, img:"unit/heavy_tank_1.png"}, {x:2, y:8, img:"unit/heavy_tank_2.png"}, {x:3, y:8, img:"unit/heavy_tank_3.png"}, {x:4, y:8, img:"unit/heavy_tank_4.png"}], 
  [null, {x:5, y:8, img:"unit/light_artillery_1.png"}, {x:6, y:8, img:"unit/light_artillery_2.png"}, {x:7, y:8, img:"unit/light_artillery_3.png"}, {x:8, y:8, img:"unit/light_artillery_4.png"}], 
  [null, {x:9, y:8, img:"unit/medium_artillery_1.png"}, {x:10, y:8, img:"unit/medium_artillery_2.png"}, {x:11, y:8, img:"unit/medium_artillery_3.png"}, {x:0, y:9, img:"unit/medium_artillery_4.png"}], 
  [null, {x:1, y:9, img:"unit/heavy_artillery_1.png"}, {x:2, y:9, img:"unit/heavy_artillery_2.png"}, {x:3, y:9, img:"unit/heavy_artillery_3.png"}, {x:4, y:9, img:"unit/heavy_artillery_4.png"}], 
  [null, {x:5, y:9, img:"unit/antiair_1.png"}, {x:6, y:9, img:"unit/antiair_2.png"}, {x:7, y:9, img:"unit/antiair_3.png"}, {x:8, y:9, img:"unit/antiair_4.png"}], 
  [null, {x:9, y:9, img:"unit/sam_1.png"}, {x:10, y:9, img:"unit/sam_2.png"}, {x:11, y:9, img:"unit/sam_3.png"}, {x:0, y:10, img:"unit/sam_4.png"}], 
  [null, {x:1, y:10, img:"unit/copter_1.png"}, {x:2, y:10, img:"unit/copter_2.png"}, {x:3, y:10, img:"unit/copter_3.png"}, {x:4, y:10, img:"unit/copter_4.png"}], 
  [null, {x:5, y:10, img:"unit/interceptor_1.png"}, {x:6, y:10, img:"unit/interceptor_2.png"}, {x:7, y:10, img:"unit/interceptor_3.png"}, {x:8, y:10, img:"unit/interceptor_4.png"}], 
  [null, {x:9, y:10, img:"unit/bomber_1.png"}, {x:10, y:10, img:"unit/bomber_2.png"}, {x:11, y:10, img:"unit/bomber_3.png"}, {x:0, y:11, img:"unit/bomber_4.png"}], 
  [null, {x:1, y:11, img:"unit/apc_1.png"}, {x:2, y:11, img:"unit/apc_2.png"}, {x:3, y:11, img:"unit/apc_3.png"}, {x:4, y:11, img:"unit/apc_4.png"}], 
  [null, {x:5, y:11, img:"unit/transport_copter_1.png"}, {x:6, y:11, img:"unit/transport_copter_2.png"}, {x:7, y:11, img:"unit/transport_copter_3.png"}, {x:8, y:11, img:"unit/transport_copter_4.png"}], 
  [null, {x:9, y:11, img:"unit/cargo_ship_1.png"}, {x:10, y:11, img:"unit/cargo_ship_2.png"}, {x:11, y:11, img:"unit/cargo_ship_3.png"}, {x:0, y:12, img:"unit/cargo_ship_4.png"}], 
  [null, {x:1, y:12, img:"unit/gunboat_1.png"}, {x:2, y:12, img:"unit/gunboat_2.png"}, {x:3, y:12, img:"unit/gunboat_3.png"}, {x:4, y:12, img:"unit/gunboat_4.png"}], 
  [null, {x:5, y:12, img:"unit/aaboat_1.png"}, {x:6, y:12, img:"unit/aaboat_2.png"}, {x:7, y:12, img:"unit/aaboat_3.png"}, {x:8, y:12, img:"unit/aaboat_4.png"}], 
  [null, {x:9, y:12, img:"unit/cruiser_1.png"}, {x:10, y:12, img:"unit/cruiser_2.png"}, {x:11, y:12, img:"unit/cruiser_3.png"}, {x:0, y:13, img:"unit/cruiser_4.png"}]], 
 [
  [{x:1, y:13, img:"gui/health_0.png"}, {x:2, y:13, img:"gui/health_1.png"}, {x:3, y:13, img:"gui/health_2.png"}, {x:4, y:13, img:"gui/health_3.png"}, {x:5, y:13, img:"gui/health_4.png"}, {x:6, y:13, img:"gui/health_5.png"}, {x:7, y:13, img:"gui/health_6.png"}, {x:8, y:13, img:"gui/health_7.png"}, {x:9, y:13, img:"gui/health_8.png"}, {x:10, y:13, img:"gui/health_9.png"}]]];